---
title: 'EKN-812: Problem Set 2'
author:
date: 
output: pdf_document
bibliography: ../../../../../library.bib
biblio-style: authordate1
geometry: margin=1in
---

_There are 95 points available on this problems set. It will be graded out of 80, i.e. there are 15 bonus points available._

**Due Date: March 7, 2019** 

1. Suppose students have to take an exam with $N$ questions. The time available for the exam is $T$, and the score on each question is a function of the student's level of knowledge, $K$, and the amount of time he or she spends on each question: 
$$
S_i = f_i(t_i, K).
$$
Assume that $f_i$ is increasing in $t_i$ and $K$ for each question $i$. Also, each question $i$ has a maximum of $\overline{S}_i$ points available. 

    (a) If students try to maximize their total score on the exam, how much time will they spend on each question? Work out the solution for the particular case 
    $$
    f_i(t_i, K) = \min\{Kt_i^\theta, \overline{S}_i\}.
    $$
    Would any student ever not attempt to answer a question at all? When will this happen? [**Hint**: consider the case $\theta < 1$ and $\theta \geq 1$ separately.]
    
    (b) Would any student ever get the maximum possible score for a question? Which ones? 

    (c) How would your answers to (a) and (b) change if the production function was 
    $$
    f_i(t_i, K) = \overline{S}_i\left[1 - \exp(-Kt_i)\right]
    $$
    Do students spend more time on the questions with more points available? Is your answer different for the well-prepared students as compared to the badly prepared ones (as defined by their $K$)?

    (d) Now suppose that all students value their time outside of the classroom at rate $v$. Set up the student's time allocation problem and write down the first-order conditions.

    (e) Do any students walk out of the exam early? Which ones?

    (f) Do students have any incentive to collude on how much time they spend on the exam?

    (g) Now suppose that the exam is graded on a "curve", e.g. the top 10\% get an A, the next 20% get a B, etc. What rationale can you think of for such a system?
    
    (h) Would students want to collude under the system of relative grading? Would they have an incentive to cheat on such an agreement?

\hfill [$8 \times 5 = 40$ points]

2. Consider a monopolist with costs $c(y)$ who sells his output in two separate markets, with demand curves $D_1(p_1)$ and $D_2(p_2)$. 

(a) Express the relationship between the equilibrium prices in the two markets in terms of the relative elasticities of demand. Let $y_1$ and $y_2$ be the quantities sold in each market, respectively.

(b) Suppose the two markets represent different countries, and the government in country 1 puts a per-unit tax of $t$ on the monopolist's product. What happens to output in market 2? 

(c) Could _total_ output actually increase as a consequence of the new tax in market 1? When will this be the case?

\hfill [$3 \times 5 = 15$ points]

3. Consider two people $a$ and $b$, both of whom face risky income prospects. In particular, suppose $a$'s income is $y_a \sim N(\mu_a, \sigma^2_a)$ and that $b$'s income is $y_b \sim N(\mu_b, \sigma^2_b)$. You can assume $y_a$ and $y_b$ are independent of each other.

 (a) Suppose $a$ has CARA preferences with absolute risk aversion $\alpha$. If she has no access to insurance markets, what is the certainty equivalent of her risky income $y_a$?

 (b) Now suppose $a$ and $b$ get married, and they agree to share their joint income as follows: $a$ will get a fraction $\pi_1$ of their joint income $y = y_a + y_b$, plus a constant transfer $\pi_0$. ($\pi_0$ could be negative, in which case it is a constant payment to $b$.) Thus, $a$ will get a random consumption allocation of $c_a = \pi_0 + \pi_1 y$, and $b$ will get $c_b = -\pi_0 + (1-\pi_0)y$.

 What is $a$'s certainty equivalent for this contract? If $b$ has CARA preferences with absolute risk aversion $\beta$, what is $b$'s certainty equivalent?

 (c) Is there a linear contract $(\pi_0, \pi_1)$ such that both $a$ and $b$ will benefit relative to their outside options? You may assume $\mu_a = \mu_b$ and $\sigma_a = \sigma_b$ from now on.

 **Hint:** see if you can find $\pi_0$ and $\pi_1$ such that the sum of $a$ and $b$'s certainty equivalents in marriage exceeds the sum of their certainty equivalents _outside_ of marriage. 
 
**Another hint:** let $\widetilde{c}^M_a$ be $a$'s certainty equivalent in marriage, and let $\widetilde{c}^S_a$ be her certainty equivalent when single; use analogous notation for $b$. A good way to start is to try and maximize their joint surplus 
$$
S(\pi_0, \pi_1) = \widetilde{c}^M_a + \widetilde{c}^M_b - \widetilde{c}^S_a - \widetilde{c}^S_b.
$$

(d) Now specialize even further to the case where $\beta = 0$ (so $b$ is risk-neutral, i.e. $v_b(c) = c$). How do the aggregate gains from marriage depend on $a$'s risk aversion $\alpha$? What does this suggest about the types of matches we should observe on the marriage market?

\hfill [$4 \times 10 = 40$ points]

